POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "itens": [
        {
            "produto_id": 1,
            "quantidade": 2
        },
        {
            "produto_id": 2,
            "quantidade": 1
        },
        {
            "produto_id": 3,
            "quantidade": 4
        },
        {
            "produto_id": 5,
            "quantidade": 3
        }
    ]
}

###
GET http://localhost:3000/api/pedidos

###
DELETE http://localhost:3000/api/pedidos/1

###
PATCH http://localhost:3000/api/pedidos/8
Content-Type: application/json

{
    "status": "finalizado"
}