// Listar todos
GET http://localhost:3000/api/produtos

###

// Listar por id
GET http://localhost:3000/api/produtos/5

###

// Cadastrar
POST http://localhost:3000/api/produtos
Content-Type: application/json

{
    "nome": "Café coado",
    "preco": 2.50,
    "estoque": 20
}

###

// Atualizar
PATCH http://localhost:3000/api/produtos/5
Content-Type: application/json

{
    "nome": "Café puro"
}

###

// Deletar
DELETE  http://localhost:3000/api/produtos/4